Added printing to the modal window
DBCDK/ding_modal pull request #3
Opened 2018-08-16 12:33 UTC by dbclkh

2018-08-16 13:27 UTC, googletorp requested changes

2018-08-16 13:27 UTC, googletorp commented on js/ding_modal.js
> +      $(window).bind("beforeprint", function () {
Den her kode laver event handlers hver gang at man vil vise en modal når der allerede er en vist. Det betyder at først gang er der et sæt handlers, anden gang 2 sæt osv.

Fordi handlers bliver lagt på window forsvinder de aldrig, så handlers er der også selvom denne kode ikke bliver kørt, bare det på et tidligere tidspunkt er blevet kørt.

Enten så skal der lægges handlers på altid og så skal de lægges på noget som afhænger af context variablen og som bliver fjernet fra DOM igen, ellers skal handles lægges på window og altid være der, og så skal der i stedet laves logik som trigger de har handles.

2018-08-17 05:15 UTC, dbclkh commented on js/ding_modal.js
> +      $(window).bind("beforeprint", function () {
Jeps - godt set. Jeg retter lige op på den.

2018-08-17 10:18 UTC, googletorp approved these changes

2018-08-17 10:21 UTC, closed without merging